item {
    id: 1
    name: 'ace'
}

item {
    id: 2
    name: 'jack'
}

item {
    id: 3
    name: 'king'
}

item {
    id: 4
    name: 'nine'
}

item {
    id: 5
    name: 'queen'
}

item {
    id: 6
    name: 'ten'
}

item {
    id: 7
    name: '§'
}